{
    "topic": "App Commands Errors",
    "pageNumber": "3",
    "type": "App Error - Could Not Get Current Branch",
    "definition": {
        "text": "There was a problem trying to get the Current Branch. Check the console for errors.",
        "updated": 1611129344277,
        "translations": [
            {
                "language": "RU",
                "text": "Возникла проблема при попытке получить текущую ветку (Current Branch). Проверьте консоль на наличие ошибок.",
                "updated": 1640236071517
            },
            {
                "language": "TR",
                "text": "Mevcut Şubeyi almaya çalışırken bir sorun oluştu. Hatalar için konsolu kontrol edin.",
                "updated": 1654392904835
            }
        ]
    },
    "paragraphs": [
        {
            "style": "Success",
            "text": "Check for the following section for details on what may have happened. After you fix the issue, you may try again.",
            "updated": 1611152967185,
            "translations": [
                {
                    "language": "RU",
                    "text": "Проверьте в следующем разделе подробную информацию о том, что могло произойти. После устранения проблемы вы можете повторить попытку.",
                    "updated": 1640236083790
                },
                {
                    "language": "TR",
                    "text": "Ne olmuş olabileceğine dair ayrıntılar için aşağıdaki bölümü kontrol edin. Sorunu çözdükten sonra tekrar deneyebilirsiniz.",
                    "updated": 1654392910178,
                    "style": "Success"
                }
            ]
        },
        {
            "style": "Title",
            "text": "Error Info",
            "updated": 1611154641024,
            "translations": [
                {
                    "language": "RU",
                    "text": "Информация об ошибке",
                    "updated": 1640236093334
                },
                {
                    "language": "TR",
                    "text": "Hata Bilgisi",
                    "updated": 1654392915752,
                    "style": "Title"
                }
            ]
        },
        {
            "style": "Text",
            "text": "In the following section, you will find the information recorded when the error occurred.",
            "translations": [
                {
                    "language": "RU",
                    "text": "В следующем разделе вы найдете информацию, записанную при возникновении ошибки.",
                    "updated": 1640236104310
                }
            ]
        },
        {
            "style": "Note",
            "text": "You will only see the information if you opened this page as a result of the error actually occurring.",
            "updated": 1611151375974,
            "translations": [
                {
                    "language": "RU",
                    "text": "Вы увидите информацию только в том случае, если вы открыли эту страницу в результате фактического возникновения ошибки.",
                    "updated": 1640236121441
                },
                {
                    "language": "TR",
                    "text": "Bu bilgileri yalnızca hatanın gerçekten meydana gelmesinin bir sonucu olarak bu sayfayı açtıysanız göreceksiniz.",
                    "updated": 1654392934232,
                    "style": "Note"
                }
            ]
        },
        {
            "style": "Subtitle",
            "text": "Error Message",
            "translations": [
                {
                    "language": "TR",
                    "text": "Hata Mesajı",
                    "updated": 1654392940462,
                    "style": "Subtitle"
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following is the Error Message of the Exception that occured at the Client:",
            "updated": 1611151299633,
            "translations": [
                {
                    "language": "RU",
                    "text": "Ниже приведено сообщение об ошибке исключения, произошедшего на клиенте:",
                    "updated": 1640236134099
                },
                {
                    "language": "TR",
                    "text": "İstemcide meydana gelen İstisnanın Hata Mesajı aşağıdadır:",
                    "updated": 1654392947232,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorMessage"
        },
        {
            "style": "Subtitle",
            "text": "Error Stack",
            "translations": [
                {
                    "language": "TR",
                    "text": "Hata Yığını",
                    "updated": 1654392952884,
                    "style": "Subtitle"
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following is the Error Stack of the Exception that occured at the Client:",
            "updated": 1611151427220,
            "translations": [
                {
                    "language": "RU",
                    "text": "Ниже приведен стек ошибок исключения, возникшего на клиенте:",
                    "updated": 1640236160531
                },
                {
                    "language": "TR",
                    "text": "İstemcide meydana gelen İstisnanın Hata Yığını aşağıdadır:",
                    "updated": 1654392958856,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorStack"
        },
        {
            "style": "Subtitle",
            "text": "Error Code",
            "translations": [
                {
                    "language": "TR",
                    "text": "Hata Kodu",
                    "updated": 1654392965034,
                    "style": "Subtitle"
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following is the Error Code of the Exception that occured at the Client:",
            "updated": 1611151443562,
            "translations": [
                {
                    "language": "RU",
                    "text": "Ниже приведен код ошибки исключения, возникшего у клиента:",
                    "updated": 1640236170146
                },
                {
                    "language": "TR",
                    "text": "İstemcide meydana gelen İstisnanın Hata Kodu aşağıdadır:",
                    "updated": 1654392970662,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorCode"
        },
        {
            "style": "Subtitle",
            "text": "Error Details",
            "translations": [
                {
                    "language": "TR",
                    "text": "Hata Detayları",
                    "updated": 1654392976425,
                    "style": "Subtitle"
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following are all the Error details of the Exception that occured at the Client:",
            "translations": [
                {
                    "language": "RU",
                    "text": "Ниже приведены все детали ошибки исключения, возникшего у клиента:",
                    "updated": 1640236189694
                },
                {
                    "language": "TR",
                    "text": "Aşağıda, İstemcide meydana gelen İstisnanın tüm Hata ayrıntıları yer almaktadır:",
                    "updated": 1654392982502,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorDetails"
        },
        {
            "style": "Text",
            "text": ""
        }
    ]
}